<!-- 
Kuin syntax definitions for Sublime Text 2
(kuin.tmLanguage)
maintainer: syamn <@starlightp>

How to use:
1. Open your "Packages" directory (Preferences/Browse Packages...)
2. Open "Kuin" directory (make it if not exists)
3. Clone this file
-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
	<array>
		<string>kn</string>
	</array>
	<key>name</key>
	<string>Kuin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>comment.comment.kuin</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kuin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kuin</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kuin</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.kuin</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(end )?func\b</string>
			<key>name</key>
			<string>entity.name.function.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(end )?class\b</string>
			<key>name</key>
			<string>entity.name.function.class.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|enum|alias)\b</string>
			<key>name</key>
			<string>storage.modifier.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(skip|block|end|do|break|ret|assert|dbg)\b</string>
			<key>name</key>
			<string>keyword.control.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|elif|while|for|throw|try|catch|finally)\b</string>
			<key>name</key>
			<string>keyword.control.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(switch|case|default)\b</string>
			<key>name</key>
			<string>keyword.control.switch.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|inf)\b</string>
			<key>name</key>
			<string>constant.language.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|const|int|bit8|bit16|bit32|bit64|float|char|bool|list|stack|queue|dict)\b</string>
			<key>name</key>
			<string>storage.type.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|&lt;&gt;|&lt;=|&lt;|&gt;=|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.kuin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:[:\+\-\*%\^~])</string>
			<key>name</key>
			<string>keyword.operator.assignment.kuin</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kuin</string>
	<key>uuid</key>
	<string>9360664a-7492-4358-8410-4353982f2921</string>
</dict>
</plist>
